# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  aws-s3: circleci/aws-s3@2.0.0
workflows: # Define a Workflow running the build job, then the deploy job
  version: 2
  build-deploy: # Make a workflow to build and deploy your project
    jobs:
      - build:
        filters:
          branches:
            only:
              - develop
              - main
              - circleci-project-setup
jobs: # Define the build and deploy jobs
  build:
    docker:
      - image: circleci/python:3.8.3
    steps:
      - checkout
      - run:
          command: |
              aws s3 sync --delete . s3://fecodepub
              echo "Successfully Hello iron "
          name: echo Test
