# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
  aws-s3: circleci/aws-s3@2.0.0
  s3: ngs/s3-deploy@0.0.1
workflows: # Define a Workflow running the build job, then the deploy job
  version: 2
  jobs: # Define the build and deploy jobs
    build:
      steps:
        - aws-s3/sync:
          arguments: | # Optional arguments
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-region: AWS_REGION_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
          from: .
          to: 's3://fecodepub'
          overwrite: true # default is false
